# Generated by Django 3.0.4 on 2020-03-09 11:39

import book.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateField(auto_now_add=True)),
                ('text_book', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('1', 'sell'), ('2', 'buy')], max_length=1)),
                ('price', models.FloatField()),
                ('picture', models.ImageField(upload_to=book.models.user_directory_path)),
                ('status', models.CharField(choices=[('1', 'open'), ('2', 'closed')], max_length=1)),
                ('create_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
