# Generated by Django 3.0.4 on 2020-03-09 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('create_date', models.DateField(auto_now_add=True)),
                ('create_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic_message_create_by', to='book.Post')),
                ('post_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.Post')),
            ],
        ),
    ]
