# Generated by Django 3.0.4 on 2020-03-10 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topic', '0002_auto_20200309_1142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
